name: "Pipeline"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: flos-ui
    steps:
      - name: Code checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build project
        run: yarn build
      - name: Run unit tests
        env:
          CI: true
        run: yarn test
      - name: Build storybook
        run: yarn build-storybook
      - name: Chromatic test
        uses: chromaui/action@v1
        with:
          appCode: ${{ secrets.CHROMATIC_APP_CODE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: storybook-static
      - name: Create release
        if: github.ref == 'refs/heads/master'
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}